### 12.09 
#### 编写一个异常类```MyException```，再编写一个类```Student```，该类有一个产生异常的方法```speak(int m)```，要求参数```m```的值大于1000时，方法抛出一个
#### ```MyException```对象。最后编写主类，在方法中创建```Student```对象，让该对象调用```speak()```方法

略微改了一点点，
```12_09.java

import static java.lang.System.out;

public class Student {
	//定义方法，抛出异常
		static int student(int number) throws MyException{
			if(number>1000)
				out.println("错了");
			return number;
		}
	public static void main(String[] args) {
		// TODO 自动生成的方法存根
		try {
			int res=student(1020);
			out.println(res);
		}catch(MyException e) {
			out.println(e);				//输出异常信息
		}
	}

}

```

### 12.10
#### 创建类```Number```,通过类中的方法```count```可得到任意两个数相乘的结果，并在调用该方法的主方法中使用```try-catch```语句捕捉可能发生的异常。

```Number.java
import static java.lang.System.out;

public class Number {

	static int quotient(int x,int y) throws MyException{		//定义方法抛出异常
		if(x*y==0)
			throw new MyException("结果不能为0");
		return x*y;
	}
	
	public static void main(String[] args) {
		// TODO 自动生成的方法存根
		try {
			int res=quotient(3, 0);
		}catch(MyException e) {						//处理自定义异常
			out.println(e.getMessage());			//输出异常信息
		}catch(Exception e) {						//处理其他异常
			out.println("程序发生了其他的异常");		//输出提示信息
		}
	}

}

输出：
结果不能为0


```


### 12.11
#### 创建类```Computer```，该类中有一个计算两个数的最大公约数的方法，如果向该方法传递负整数，该方法就会抛出自定义异常

```Computer.java
import static java.lang.System.out;

public class Computer {

	
	static int Gcd(int x,int y) throws MyException{		//定义方法抛出异常
		if(x<0||y<0)
			throw new MyException("传参不能为负");
		return gcd(x,y);
	}
	//int gcd(int x,int y){不能静态引用非静态方法
	static int gcd(int x,int y) {
		return x==0?y:gcd(y,x%y);
	}
	
	public static void main(String[] args) {
		// TODO 自动生成的方法存根
		try {
			int res=Gcd(-1,2);
		}catch(MyException e) {						//处理自定义异常
			out.println(e.getMessage());			//输出异常信息
		}catch(Exception e) {						//处理其他异常
			out.println("程序发生了其他的异常");		//输出提示信息
		}
	}
}
```








